#!/usr/bin/env bash
set -e
# Get all devices by name
# SwitchAudioSource -a | grep "(output)" | awk '{$NF=""; print $0}'

# Check if a device is connected
function has_device() {
  SwitchAudioSource -a | grep "${@}" > /dev/null
}

function set_device() {
  SwitchAudioSource -s "${@}"
  echo "Switching to ${@}"
}

# Check for devices and attempt to set them one by one
function check_and_set_audio() {
  for device in "${@}"; do
    if has_device "${device}"; then
      set_device "${device}"
      exit 0
    fi
  done
  echo "Could not find desired devices."
  set_device "Build-in Output"
}

check_and_set_audio "Method Wireless" "Elgato Dock"
