#!/usr/bin/env bash
set -e

if hash idea >/dev/null 2>&1; then
  if [ -z "${1}" ] || [ "${1}" == "." ]; then
    project_directory="$(pwd)"
  fi
  idea "${project_directory}" >/dev/null 2>&1 &
  disown
else
  echo "idea script is not in path, that's a no bueno" 1>&2
  exit 1
fi
