#!/usr/bin/env bash

for port in "${@}"; do
  process_id="$(lsof -t -i :${port})"
  # If we didn't find a process id, then move on to the next
  # port to check.
  if [ -z "${process_id}" ]; then
    continue
  fi
  # We found a port. Kill the app
  echo "Found process ${process_id} bound to localhost:${port}, sending KILL signal"
  kill -9 "${process_id}"
done
