#!/usr/bin/env bash

if [ $# -ne 1 ]; then
  echo "One and only one argument expected, which will be the artifact version."
fi

function setmvn()
{
  mvn versions:set -DnewVersion="${1}"
  mvn versions:update-child-modules
}

original_version="$(mvn org.apache.maven.plugins:maven-help-plugin:2.1.1:evaluate -Dexpression=project.version|grep -Ev '(^\[|Download\w+:)')"

setmvn "${1}"
mvn install -Dmaven.test.skip=true -Dgithub.site.skip=true -Dgpg.skip=true
install_failed="${?}"
# Rest back to original name for the sake of version control."
setmvn "${original_version}"
#  If the install failed, let us know.
if [[ "${install_failed}" -ne "0" ]]; then
  echo "=========================="
  echo "= THIS FAILED TO INSTALL ="
  echo "=========================="
else
  echo "=========================="
  echo "= INSTALL WORKED LOCALLY ="
  echo "=========================="
fi
