tap 'caskroom/cask'

# standard terminal setup
brew 'zsh'
brew 'zsh-completions'
brew 'coreutils'
brew 'findutils'
brew 'bash'
brew 'brew-cask-completion'
brew 'grep'

# terminal utils
brew 'tree'
brew 'm-cli'
brew 'wget'
brew 'watch'
brew 'shellcheck'
brew 'imagemagick'
brew 'graphviz'
brew 'unrar'
brew 'jq'

# dev specific stuff
brew 'git'
brew 'git-secrets'
brew 'boost'
brew 'boost-python'
brew 'sdl'
brew 'sdl_image'
brew 'sdl_mixer'
brew 'sdl_ttf'
brew 'awscli'
brew 'clang-format'
brew 'cmake'
brew 'node'
brew 'libvirt'
brew 'dos2unix'

# wine
brew 'wine'
brew 'winetricks'

# golang
brew 'go'

# python
brew 'python'
brew 'python3'

# java
cask 'java8'
cask 'jetbrains-toolbox'
brew 'maven'
brew 'gradle'
brew 'kotlin'
cask 'android-sdk'
cask 'android-ndk'
brew 'jenv'

# virtualization
brew 'qemu'
cask 'virtualbox'
cask 'docker'
cask 'kitematic'

# misc
cask 'atom'
cask 'firefox'
cask 'google-chrome'
cask 'gimp'
cask 'iterm2'
cask 'postman'
cask 'robo-3t'
cask 'sourcetree'
cask 'spotify'
cask 'tunnelbear'
cask 'xscreensaver'
brew 'chromedriver'
brew 'geckodriver'
brew 'exercism'
brew 'ffmpeg'
brew 'youtube-dl'
brew 'findutils'
