tap 'caskroom/cask'
tap 'caskroom/versions'

# standard terminal setup
brew 'zsh'
brew 'zsh-completions'
brew 'coreutils'
brew 'findutils'
brew 'bash'
brew 'brew-cask-completion'
brew 'grep'
brew 'ack'
brew 'gpg2'

# terminal utils
brew 'tree'
brew 'm-cli'
brew 'wget'
brew 'watch'
brew 'shellcheck'
brew 'imagemagick'
brew 'graphviz'
brew 'unrar'
brew 'jq'
brew 'switchaudio-osx'

# dev specific stuff
brew 'git'
brew 'git-secrets'
brew 'boost'
brew 'boost-python'
#brew 'sdl'
#brew 'sdl_image'
#brew 'sdl_mixer'
#brew 'sdl_ttf'
brew 'sdl2{,_image,_ttf,_mixer}'
brew 'awscli'
brew 'clang-format'
brew 'cmake'
brew 'node'
brew 'libvirt'
brew 'dos2unix'
brew 'jmeter'

# wine
cask 'xquartz'
brew 'wine'
brew 'winetricks'

# java
cask 'java8'
cask 'jetbrains-toolbox'
brew 'maven'
brew 'gradle'
brew 'kotlin'
cask 'android-sdk'
cask 'android-ndk'
brew 'jenv'

# golang
brew 'go'

# python
brew 'python'
brew 'python3'
# Disabling anaconda, usually more tempermental than it's worth
# cask 'anaconda'

# haskell, this cask seems to be dead.
# cask 'haskell-platform'

# virtualization
brew 'qemu'
cask 'virtualbox'
cask 'docker'
cask 'kitematic'

# misc
# cask 'atom'
cask 'visual-studio-code'
cask 'firefox'
cask 'google-chrome'
cask 'gimp'
cask 'iterm2'
cask 'postman'
cask 'robo-3t'
cask 'sourcetree'
cask 'spotify'
cask 'tunnelbear'
cask 'xscreensaver'
cask 'chromedriver'
brew 'geckodriver'
brew 'exercism'
brew 'ffmpeg'
brew 'youtube-dl'

mas 'Magnet', id: 441258766
mas 'iHosts', id: 1102004240
mas 'Telegram', id: 747648890
mas 'Cuppa - Tea Timer', id: 1297865739
